services:
  - type: web
    name: project-megatron-api
    env: python
    rootDir: .
    buildCommand: |
      python -m pip install --upgrade pip
      pip install uv
      uv sync --frozen
      source .venv/bin/activate
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
