services:
  - type: web
    name: project-megatron-api
    env: python
    rootDir: .
    buildCommand: |
      pip install uv
      uv sync --frozen
    startCommand: .venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT
